name: Update Haystack version in README.md

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Haystack version, e.g v1.13.0, v1.13.1"
        required: true
        type: string

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README.md
        run: |
          sed -i -r 's/Haystack is on v[0-9]+\.[0-9]+\.[0-9]+/Haystack is on ${{ inputs.version }}/g' profile/README.md

      - name: Commit and open PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-haystack-version
          git commit --all -m "Update Haystack version"
          git push -u origin update-haystack-version
          gh pr create -B main --title 'Bump Haystack version to ${{ inputs.version }}' --fill -r devrel
